# Site settings
name: Qiu Blog
email: qiutianyou95@qq.com
author: Qiu
url: https://qiutianyou.github.io
resume_site:
github: https://github.com/qiutianyou/
baseurl: "/qiu"
description: 邱天佑的个人博客!
meta_description: 邱天佑;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: I am a software engineer,I will change the world
banner:  学如逆水行舟，不进则退。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: qiutianyou

# Build settings
markdown: kramdown

baidu_analysis: a68b715bdac4c5da8ba5e62a392c459c
